Repository TheEmpty123/OUR_Pomodoro, pull requests merged in 2025-06, with the labels that each got.

#41 Room storage
  FE/app/src/main/java/com/mobile/pomodoro/Plan/PlanActivity.java
  FE/app/src/main/java/com/mobile/pomodoro/Todo/TodoActivity.java
  FE/app/src/main/java/com/mobile/pomodoro/Todo/TodoPopupFragment.java
  FE/app/src/main/java/com/mobile/pomodoro/room/AppDatabase.java
  FE/app/src/main/java/com/mobile/pomodoro/room/RoomUtils.java
  FE/app/src/main/java/com/mobile/pomodoro/room/entity/DailyTask.java
  FE/app/src/main/java/com/mobile/pomodoro/room/repo/DailyTaskRepository.java
  FE/app/src/main/java/com/mobile/pomodoro/room/repo/PlanRepository.java
  FE/app/src/main/java/com/mobile/pomodoro/room/repo/SingleThreadRepo.java
  FE/app/src/main/java/com/mobile/pomodoro/room/repo/TodoRepository.java
Labels: enhancement, wontfix, new

#42 Save plan, HomePage recent plan
  FE/app/src/main/java/com/mobile/pomodoro/HomePage.java
  FE/app/src/main/java/com/mobile/pomodoro/Plan/PlanActivity.java
  FE/app/src/main/java/com/mobile/pomodoro/mapper/PlanMapper.java
  FE/app/src/main/java/com/mobile/pomodoro/response_dto/PlanResponseDTO.java
  FE/app/src/main/java/com/mobile/pomodoro/response_dto/SavePlanResponseDTO.java
  FE/app/src/main/java/com/mobile/pomodoro/service/PomodoroAPI.java
  FE/app/src/main/java/com/mobile/pomodoro/utils/SessionManager.java
  FE/app/src/main/res/layout/activity_homepage.xml
Labels: enhancement

#43 Fix SavePlan
  FE/app/src/main/java/com/mobile/pomodoro/HomePage.java
  FE/app/src/main/java/com/mobile/pomodoro/Plan/PlanActivity.java
Labels: bug
